# Generated by Django 3.1.3 on 2020-11-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('prior_ailments', models.TextField()),
                ('bed_num', models.CharField(max_length=5)),
            ],
        ),
    ]
