# Generated by Django 3.1.3 on 2020-11-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='recovering', max_length=50),
            preserve_default=False,
        ),
    ]
